<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>上传SO文件</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->tag->stylesheetLink('bootcss/css/bootstrap.css');?>
<?php echo $this->tag->javascriptInclude('js/jquery-1.10.2.min.js');?>
<?php echo $this->tag->javascriptInclude('bootcss/js/bootstrap.js');?>
<style type="text/css">
body {
	padding-top: 70px;
}
</style>
</head>

<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target="#navbar-data-div">
				<span class="sr-only">切换</span> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
			</button>
			<?php echo \Phalcon\Tag::linkTo(array("view",'崩溃报告','class'=>'navbar-brand'));?>
		</div>
		<div class="collapse navbar-collapse" id="navbar-data-div">
			<ul class="nav navbar-nav">
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("view",'查看'));?></li>
				<li class="active"><?php echo \Phalcon\Tag::linkTo(array('upload','上传'))?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("archieve",'历史归档'));?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("view/recent",'最新崩溃'));?></li>
			<li class=""><?php echo \Phalcon\Tag::linkTo(array("manage/index",'SO管理'));?></li>
			</ul>
		</div>
	</div>
	<div class="container">
		<h2>
			上传SO文件
			<div class="btn-group pull-right"><?php echo \Phalcon\Tag::linkTo(array('upload/index','上传DMP文件','class'=>'btn btn-primary'));?></div>
		</h2>
<?php $this->flashSession->output();?>

		<form action="" class="form-horizontal" enctype="multipart/form-data"
			method="post">
			<div class="form-group">
				<label for="project" class="col-sm-2 control-label">项目</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" id="project" name="project" />
				</div>
			</div>
			<div class="form-group">
				<label for="versionCode" class="col-sm-2 control-label">版本号</label>
				<div class="col-sm-10">
					<input type="number" class="form-control" id="versionCode"
						name="versionCode" />
				</div>
			</div>
			<div class="form-group">
				<label for="file" class="col-sm-2 control-label">SO文件</label>
				<div class="col-sm-10">
					<input type="file" class="form-control btn btn-default" id="file"
						name="file" />
				</div>
			</div>
			<div class="form-group">
				<button type="submit" class="form-control btn btn-primary">上传</button>
			</div>

		</form>
	</div>
</body>

</html>