<div>
	<form method="POST" class="form-horizontal"
		enctype="multipart/form-data">
		<div class="form-group">
			<label class="control-label col-sm-2" for="package">Package</label>
			<div class="col-sm-8">
				<input class="form-control " type="text" name="package" id="package"
					value="<?php echo @$package;?>" />
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-2" for="image">Image</label>
			<div class="col-sm-8">
				<input class="form-control " type="file" name="image" id="image" />
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-2">Type</label>
			<div class="col-sm-8">
				<label><input type="radio" name="type" value="featured"
					checked="checked"> featured</label> <label><input type="radio"
					name="type" value="other"> other</label>
			</div>
		</div>
		<div class="form-group">
			<label class="control-label col-sm-2" for="url">URL (Optional)</label>
			<div class="col-sm-8">
				<input class="form-control " type="text" name="url" id="url"
					value="<?php echo @$url;?>" />
			</div>
		</div>
		<div class="form-group">
			<input type="submit" class="col-sm-offset-4 col-sm-4 btn btn-primary"
				value="Save" />
		</div>
	</form>
	<div><?php $this->flash->output();?></div>
</div>