<form action="" method="post" class="form-horizontal">
	<div class="form-group">
		<label for="" class="control-label col-sm-2">ID</label>
		<div class="col-sm-10">
			<span class="form-control" disabled><?php echo $user->account_id;?></span>
		</div>
	</div>
	<div class="form-group">
		<label for="" class="control-label col-sm-2">Nickname</label>
		<div class="col-sm-10">
			<span class="form-control" disabled><?php echo $user->nickname;?></span>
		</div>
	</div>
	<div class="form-group">
		<label for="chip" class="control-label col-sm-2">Chip</label>
		<div class="col-sm-10">
			<input type="text" name="chip" id="chip" value="0"
				class="form-control" />
		</div>
	</div>
	<div class="form-group">
		<label for="diamond" class="control-label col-sm-2">Diamond</label>
		<div class="col-sm-10">
			<input type="text" name="diamond" id="diamond" value="0"
				class="form-control" />
		</div>
	</div>
	<div class="form-group">
		<button type="submit" class="col-sm-4 col-sm-offset-4 btn btn-primary">Charge</button>
		<input type="hidden"
			name="<?php echo $this->security->getTokenKey();?>"
			value="<?php echo $this->security->getToken();?>" />
	</div>
	</div>
</form>