<!DOCTYPE html>
<html>
<head>
<title><?php echo $title;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->tag->stylesheetLink('bootcss/css/bootstrap.css');?>
<?php echo $this->tag->javascriptInclude('js/jquery-1.10.2.min.js');?>
<?php echo $this->tag->javascriptInclude('bootcss/js/bootstrap.js');?>
<style type="text/css">
body {
	padding-top: 70px;
}
</style>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target="#navbar-data-div">
				<span class="sr-only">切换</span> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
			</button>
			<?php echo \Phalcon\Tag::linkTo(array("view",'崩溃报告','class'=>'navbar-brand'));?>
		</div>
		<div class="collapse navbar-collapse" id="navbar-data-div">
			<ul class="nav navbar-nav">
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("view",'查看'));?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array('upload','上传'))?></li>
				<li class="active"><?php echo \Phalcon\Tag::linkTo(array("archieve",'历史归档'));?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("view/recent",'最新崩溃'));?></li>
			<li class=""><?php echo \Phalcon\Tag::linkTo(array("manage/index",'SO管理'));?></li>
			</ul>
		</div>
	</div>
	<div class="container">
		<table class="table table-striped table-hover table-responsive">
			<thead>
				<tr>
					<th>日期</th>
					<th>项目</th>
					<th>包含数量</th>
				</tr>
			</thead>
			<?php foreach ($records as $record):?>
			<tr>
				<td><?php echo $record->archieve;?></td>
				<td><?php echo $record->project;?></td>
				<td><a class="label label-success"
					href="<?php echo $this->getDI()->get('fileUrl')->get('archieve/'.$record->archieve.'.'.$record->project.'.tar.gz');?>"><?php echo $record->count;?></a></td>
			</tr>
			<?php endforeach;?>
		</table>
	</div>
</body>
</html>