<!DOCTYPE html>
<html>
<head>
<title><?php echo $title;?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->tag->stylesheetLink('bootcss/css/bootstrap.css');?>
<?php echo $this->tag->javascriptInclude('js/jquery-1.10.2.min.js');?>
<?php echo $this->tag->javascriptInclude('bootcss/js/bootstrap.js');?>
<style type="text/css">
body {
	padding-top: 70px;
}
</style>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target="#navbar-data-div">
				<span class="sr-only">切换</span> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
			</button>
			<?php echo \Phalcon\Tag::linkTo(array("view",'崩溃报告','class'=>'navbar-brand'));?>
		</div>
		<div class="collapse navbar-collapse" id="navbar-data-div">
			<ul class="nav navbar-nav">
				<li class="active"><?php echo \Phalcon\Tag::linkTo(array("view",'查看'));?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array('upload','上传'))?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("archieve",'历史归档'));?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("view/recent",'最新崩溃'));?></li>
			<li class=""><?php echo \Phalcon\Tag::linkTo(array("manage/index",'SO管理'));?></li>
			</ul>
		</div>
	</div>
	<div class="container">
		<ol class="breadcrumb">
			<li><?php echo \Phalcon\Tag::linkTo('view','首页');?></li>
			<li><?php echo \Phalcon\Tag::linkTo(array(array('for'=>'ViewCrash::showByStatus','status'=>$params['status'],'project'=>$params['project'],'versionCode'=>$params['versionCode']),$params['status']));?></a></li>
			<li><?php echo \Phalcon\Tag::linkTo(array(array('for'=>'ViewCrash::showByProject','status'=>$params['status'],'project'=>$params['project'],'versionCode'=>$params['versionCode']),$params['project']));?></li>
			<li><?php echo \Phalcon\Tag::linkTo(array(array('for'=>'ViewCrash::showByVersionCode','status'=>$params['status'],'project'=>$params['project'],'versionCode'=>$params['versionCode']),$params['versionCode']));?></li>
			<li class="active"><?php echo $params['md5']?></li>
		</ol>
		<pre>
			<code>
<?php echo $stack;?></code>
</pre>
		<table class="table table-striped table-hover table-responsive">
			<thead>
				<tr>
					<th class="col-md-1">制造商</th>
					<th class="col-md-1">品牌</th>
					<th class="col-md-1">型号</th>
					<th class="col-md-1">安卓API</th>
					<th class="col-md-4">DMP文件</th>
					<th class="col-md-2">时间</th>
					<th class="col-md-1">详情</th>
				</tr>
			</thead>
		<?php foreach ($records as $record):?>
		<tr>
				<td><?php echo $record->manufacturer;?></td>
				<td><?php echo $record->brand;?></td>
				<td><?php echo $record->model;?></td>
				<td><?php echo $record->androidSdkInt;?></td>
				<td><?php echo $record->file_name;?></td>
				<td><?php echo $record->time_stamp;?></td>
				<td><a
					href="<?php echo $this->url->get(array('for'=>'ViewCrash::showByRecordID','record_id'=>$record->record_id));?>">详情</a></td>
			</tr>
		<?php endforeach;?>
	</table>
	</div>
</body>
</html>