<?php echo $this->tag->getDoctype();?>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Welcome to GY Texas Holdem</title>
<!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet"
	href="//cdn.jsdelivr.net/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- 可选的Bootstrap主题文件（一般不用引入） -->
<!-- 
<link rel="stylesheet"
	href="//cdn.jsdelivr.net/bootstrap/3.2.0/css/bootstrap-theme.min.css">  -->
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

<link rel="stylesheet"
	href="<?php echo $this->url->getStatic('css/bootcss-ext.css');?>">
<script src="<?php echo $this->url->getStatic('js/jquery.boot.js');?>"></script>
</head>

<body>
	<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">GameYep</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse"
				id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a href="<?php echo $this->url->get('');?>">Home</a></li>
					<li><a href="<?php echo $this->url->get('shop');?>">Shop</a></li>
					<li><a href="<?php echo $this->url->get('bank');?>">Bank</a></li>
					<li><a href="<?php echo $this->url->get('log');?>">Log</a></li>
					<li><a href="<?php echo $this->url->get('mina');?>">MINA</a></li>
					<li><a href="<?php echo $this->url->get('special-offer');?>">Special
							Offer</a></li>
					<li><a href="<?php echo $this->url->get('monthly-offer');?>">Monthly
							Offer</a></li>
					<li><a href="<?php echo $this->url->get('news');?>">News</a></li>
					<li><a href="<?php echo $this->url->get('maintaince');?>">Maintaince</a></li>
					<!-- 
				<li class="dropdown"><a href="#" class="dropdown-toggle"
					data-toggle="dropdown">Dropdown <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">
						<li><a href="#">Action</a></li>
						<li><a href="#">Another action</a></li>
						<li><a href="#">Something else here</a></li>
						<li class="divider"></li>
						<li><a href="#">Separated link</a></li>
						<li class="divider"></li>
						<li><a href="#">One more separated link</a></li>
					</ul></li>
				-->
				</ul>
				<!-- 
			<form class="navbar-form navbar-left" role="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search">
				</div>
				<button type="submit" class="btn btn-default">Submit</button>
			</form>
			 -->
				<ul class="nav navbar-nav navbar-right">
					<li><a href="javascript:void(0)" id="server-time"><?php echo date('Y-m-d H:i:s');?></a></li>
					<?php if ($this->session->get('PHP_AUTH_USER',false)) {?>
					<li class="dropdown"><a href="#" class="dropdown-toggle"
						data-toggle="dropdown"> Signed in as <span
							class="badge text-primary"><?php echo ($this->session->get('PHP_AUTH_USER'));?></span>
							<span class="caret"></span></a>

						<ul class="dropdown-menu" role="menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li class="divider"></li>
							<li><a href="<?php echo $this->url->get('index/logout');?>">Logout</a></li>
						</ul></li>
						<?php }else{?>
						<li><button class="btn navbar-btn btn-primary"
							onclick="javascript:window.location.href='<?php echo $this->url->get('index/auth',array('redirect'=>$this->url->get($_GET['_url'])));?>';">Login</button></li>
						<?php }?>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container-fluid -->
	</nav>
	<div class="container"><?php echo $this->getContent(),PHP_EOL;?></div>
	<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
	<script src="//cdn.jsdelivr.net/jquery/1.11.1/jquery.min.js"></script>

	<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
	<script src="//cdn.jsdelivr.net/bootstrap/3.2.0/js/bootstrap.min.js"></script>
	<script src="<?php echo $this->url->getStatic('js/jquery.post.js');?>"></script>
	<script
		src="<?php echo $this->url->getStatic('js/bootstrap.navbar.indicator.js');?>"></script>
</body>
</html>