<!DOCTYPE html>
<html>
<head>
<title>管理</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php echo $this->tag->stylesheetLink('bootcss/css/bootstrap.css');?>
<?php echo $this->tag->javascriptInclude('js/jquery-1.10.2.min.js');?>
<?php echo $this->tag->javascriptInclude('bootcss/js/bootstrap.js');?>
<style type="text/css">
body {
	padding-top: 70px;
}
</style>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse"
				data-target="#navbar-data-div">
				<span class="sr-only">切换</span> <span class="icon-bar"></span> <span
					class="icon-bar"></span> <span class="icon-bar"></span>
			</button>
			<?php echo \Phalcon\Tag::linkTo(array("view",'崩溃报告','class'=>'navbar-brand'));?>
		</div>
		<div class="collapse navbar-collapse" id="navbar-data-div">
			<ul class="nav navbar-nav">
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("view",'查看'));?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array('upload','上传'))?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("archieve",'历史归档'));?></li>
				<li class=""><?php echo \Phalcon\Tag::linkTo(array("view/recent",'最新崩溃'));?></li>
				<li class="active"><?php echo \Phalcon\Tag::linkTo(array("manage/index",'SO管理'));?></li>
			</ul>
		</div>
	</div>
	<div class="container">
		<h2>管理</h2>
		<?php echo $this->flashSession->output();?>
		
			<h3>
			<div class="well">
				删除SO
				<form action="" class="form-inline pull-right" method="post">
					<div class="form-group">
						<label class="sr-only" for="project">项目</label> <input type="text"
							class="form-control" id="project" name="project" placeholder="项目">
					</div>
					<div class="form-group">
						<label class="sr-only" for="exampleInputPassword2">版本号</label> <input
							type="number" class="form-control" id="versionCode"
							name="versionCode" placeholder="版本号">
					</div>
					<input type="hidden" name="action" value="delete_so">
					<button type="submit" class="btn btn-primary">立即删除</button>
				</form>
			</div>
		</h3>

	</div>
</body>
</html>