<!-- //LAYOUT -->
<div class="site-wrapper">
	<div class="site-wrapper-inner">
		<div class="cover-container">
			<div class="masthead clearfix">
				<div class="inner">
					<h3 class="masthead-brand">Solidarity</h3>
					<ul class="nav masthead-nav">
						<li><a href="<?php echo $this->url->get('');?>">Home</a></li>
						<li class="active"><a href="<?php echo $this->url->get('ads');?>">Ads Manager</a></li>
						<li><a href="<?php echo $this->url->get('contact');?>">Contact</a></li>
					</ul>
				</div>
			</div>

			<div class="inner cover">
				<?php echo $this->getContent(),PHP_EOL;?>
			</div>

			<div class="mastfoot">
				<div class="inner">
					<p>
						Copyright 2014 <a href="#">GameYep</a>
						<!-- , by <a href="#">@Ian</a>. -->
					</p>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- LAYOUT// -->