<div class="col-md-6 col-md-offset-3">
	<div
		class="panel <?php echo ($this->flash->has('error'))?'panel-danger':'panel-primary';?>">
		<div class="panel-heading">Login</div>
		<div class="panel-body">
			<div>
				<form action="" method="post" class="form-horizontal" role="form">

					<div class="form-group">
						<label for="username1" class="control-label col-sm-2">Username</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="username"
								id="username1" value="<?php echo $username;?>"
								placeholder="Your username" />
						</div>
					</div>
					<div class="form-group">
						<label for="password1" class="control-label col-md-2">Password</label>
						<div class="col-md-10">
							<input type="password" class="form-control" name="password"
								id="password1" value="<?php echo $password;?>"
								placeholder="Your password" />
						</div>
					</div>
					<div class="form-group">
						<div class="col-md-4 col-md-offset-4">
							<input type="submit" class="form-control btn btn-primary"
								value="Login" /> <input type="hidden"
								name="<?php echo $this->security->getTokenKey();?>"
								value="<?php echo $this->security->getToken();?>" />
						</div>
					</div>
				</form>
			</div>

		</div>
		<div class="panel-footer">
			<?php $this->flash->output();?>
			</div>
	</div>
</div>
